### ISSUE TITLE
링크 옆에 )가 껴있습니다.

### ISSUE THREAD

**Issue by qlife1146** [alanleedev/KoreaSecurityApps#29]
https://github.com/alanleedev/KoreaSecurityApps/blob/main/02_ipinside_lws_agent.md#:~:text=%EB%85%84%EC%97%90%20%EC%9E%91%EC%84%B1%EB%90%9C%20%EB%A7%A4%EB%89%B4%EC%96%BC-,),-%EC%9D%84%20%EC%B0%BE%EC%95%98%EB%8A%94%EB%8D%B0%20%EC%9D%B8%ED%84%B0%EB%A6%AC%EC%A0%A0%EC%9D%98
껴있는 부분의 하이라이트 링크입니다.

**Comment by alanleedev** [comment]
이렇게 간단한 건 issue 안만들고 바로 PR 올려주시면 될 것 같네요 ^^
collaborator로 초대할께요.
